#!/bin/csh
source /netapp/g5cwmspd/.cshrc
setenv DISPLAY :1
#cd /export/home/g0pdrrjl/g7cwmspd/cronjobs/Plots/Images
cd /netapp/g5cwmspd/cronjobs/Plots/Images
rm *jpg
#cd /export/home/g0pdrrjl/g7cwmspd/cronjobs/Plots
cd /netapp/g5cwmspd/cronjobs/Plots

# Run each script below to generate plots
#jython3 Reservoir_NwdmElev_Plots.py &
#jython3 Reservoir_MrbwmElevInflowOutflow_Plots.py &
jython3 Reservoir_MrbwmElevInflowOutflowZones_Plots.py
#jython3 Reservoir_MrbwmMinElevInflowOutflowPrecipStor_Plots.py
#jython3 Reservoir_NwoElevInflowOutflowPrecipStorZones_Plots.py
#jython3 Reservoir_NwoPrecip_Plots.py
#jython3 Reservoir_NwoRawRevElev_Plots.py
#jython3 Reservoir_NwoElevInflowOutflow6Hr_Plots.py
#jython3 Reservoir_NwkElevInflowOutflowPrecipStorZones_Plots.py
#jython3 Reservoir_NwkKanProjFlow_Plots.py
#jython3 River_NwdmStage_Plots.py
#jython3 River_NwdmStageFlow_Plots.py
#jython3 River_NwdmMoRivKanFlow_Plots.py
#jython3 River_MrbwmPirGagesStage_Plots.py
#jython3 River_MrbwmGrftFlow_Plots.py
#jython3 River_MrbwmCompareStageFlow_Plots.py
#jython3 Snowpack_NwdmSnotel_Plots.py
#jython3 Reservoir_NwoRawRevRadarElev_Plots.py
#jython3 Reservoir_NwoElevPrecip_Plots.py

echo Done
