#!/bin/csh
source /netapp/g7cwmspd/.cshrc
setenv DISPLAY :1    
cd /netapp/g7cwmspd/plotFiles/files
rm *.jpg
cd /netapp/g7cwmspd
# Uncommented scripts have been edited to include the try: finally: group that
#	will terminate all database connections. If any of the commented scripts
#	are uncommented, they will first need to be edited to include the
#	try: finally: group
    jython /netapp/g7cwmspd/plotFiles/createPlotsMRRelev2.py
    jython /netapp/g7cwmspd/plotFiles/createPlotsKanProj.py
    jython /netapp/g7cwmspd/plotFiles/createPlotsNWKres.py
    jython /netapp/g7cwmspd/plotFiles/createPlotsMRRpierre.py
    jython /netapp/g7cwmspd/plotFiles/createPlotsNWOhbia.py
    jython /netapp/g7cwmspd/plotFiles/createPlotsGRFTfcstq.py
    jython /netapp/g7cwmspd/plotFiles/NWO_Res_Elev_RawRev_Plots.py
    /netapp/g7cwmspd/plotFiles/pirMosaic.script
# Unedited scripts
#    jython /netapp/g7cwmspd/plotFiles/createPlotsMRRWaterTemp1.py
#    jython /netapp/g7cwmspd/plotFiles/createPlotsMRRelev1.py
#    jython /netapp/g7cwmspd/plotFiles/createPlotsMRRpierre.py
#    jython /netapp/g7cwmspd/plotFiles/createPlotsMRRstage.py
#    jython/netapp/g7cwmspd/plotFiles/createPlotsMRRresMin.py
#    jython/netapp/g7cwmspd/plotFiles/createPlotsMORiv2.py
#    jython/netapp/g7cwmspd/plotFiles/createPlotsMORiv1.py
#    jython/netapp/g7cwmspd/plotFiles/createPlotsMORiv.py
#    jython /netapp/g7cwmspd/plotFiles/createPlotsMRRcheckFUI.py
#    jython /netapp/g7cwmspd/plotFiles/createPlotsKanRiv.py
#    jython /netapp/g7cwmspd/plotFiles/createPlotsMRRfcastq_kg.py
#    jython /netapp/g7cwmspd/plotFiles/createPlotsMRRfcast4.py
#    jython /netapp/g7cwmspd/plotFiles/createPlotsMRRfui-qgh.py
#    jython /netapp/g7cwmspd/plotFiles/createPlotsMRRmainstem-qgh.py
#    jython /netapp/g7cwmspd/plotFiles/createPlotsMRRnonfui-qgh.py
#    jython /netapp/g7cwmspd/plotFiles/createPlotsMRRfcast5.py
#    jython /netapp/g7cwmspd/plotFiles/createPlotsMRRfcastDENE.py
#    jython /netapp/g7cwmspd/plotFiles/createPlotsMRRelev2.py
#    jython /netapp/g7cwmspd/plotFiles/createPlotsMRRpir.py

#
# Prepare to make Xwindow dump files
#
#cd /netapp/g7cwmspd/plotFiles/files
#/usr/sfw/bin/mogrify -format xwd *.jpg
#
# Move files to web and to local zone MRADS cwmspixel directory for displaying by viewpix
#
echo 'Moving files to web server staging area and to local zone.'
cd /netapp/g7cwmspd/plotFiles/files
/bin/scp *.jpg g7cwmspd@nwo-wmlocal2.nwo.usace.army.mil:/mrads/cwmspixel
echo Done
