#!/bin/csh
source /netapp/g7cwmspd/.cshrc
setenv DISPLAY :1    
#    jython /netapp/g7cwmspd/plotFiles/createPlotsMRRelev2.py
#    jython /netapp/g7cwmspd/plotFiles/createPlotsKanProj.py
     jython /netapp/g7cwmspd/plotFiles/createPlotsMRRWaterTemp1.py
     jython /netapp/g7cwmspd/plotFiles/createPlotsMRRelev1.py
#     jython /netapp/g7cwmspd/plotFiles/createPlotsMRRpierre.py
     jython /netapp/g7cwmspd/plotFiles/createPlotsMRRstage.py
#    jython /netapp/g7cwmspd/plotFiles/createPlotsNWKres.py
     jython /netapp/g7cwmspd/plotFiles/createPlotsMRRresMin.py
     jython /netapp/g7cwmspd/plotFiles/createPlotsMORiv2.py
     jython /netapp/g7cwmspd/plotFiles/createPlotsMORiv1.py
     jython /netapp/g7cwmspd/plotFiles/createPlotsMORiv.py
###     jython /netapp/g7cwmspd/plotFiles/createPlotsMRRcheckFUI.py
     jython /netapp/g7cwmspd/plotFiles/createPlotsKanRiv.py
###     jython /netapp/g7cwmspd/plotFiles/createPlotsMRRfcastq_kg.py
###     jython /netapp/g7cwmspd/plotFiles/createPlotsMRRfcast4.py
     jython /netapp/g7cwmspd/plotFiles/createPlotsMRRfui-qgh.py
     jython /netapp/g7cwmspd/plotFiles/createPlotsMRRmainstem-qgh.py
     jython /netapp/g7cwmspd/plotFiles/createPlotsMRRnonfui-qgh.py
###     jython /netapp/g7cwmspd/plotFiles/createPlotsMRRfcast5.py
###     jython /netapp/g7cwmspd/plotFiles/createPlotsMRRfcastDENE.py
	jython /netapp/g7cwmspd/plotFiles/createPlotsMRRmainstem-res2.py
	jython /netapp/g7cwmspd/plotFiles/createPlotsMRRmainstem-res.py
        jython /netapp/g7cwmspd/plotFiles/createPlotsNWKriver2-qgh.py
        jython /netapp/g7cwmspd/plotFiles/createPlotsNWOriver2-qgh.py
        jython /netapp/g7cwmspd/plotFiles/createPlotsNWOriver1-qgh.py
        jython /netapp/g7cwmspd/plotFiles/createPlotsNWKriver1-qgh.py
	jython /netapp/g7cwmspd/plotFiles/CroncompareFlows.py
        jython /netapp/g7cwmspd/plotFiles/createPlotsNWOres.py
        jython /netapp/g7cwmspd/plotFiles/createPlotsNWOusbr.py
        jython /netapp/g7cwmspd/plotFiles/createPlotsNWOstage.py
        jython /netapp/g7cwmspd/plotFiles/createPlotsNWOprecip.py
        jython /netapp/g7cwmspd/plotFiles/createPlotsNWKstage.py
#
/netapp/g7cwmspd/plotFiles/bisMosaic.script
# 
#  Prepare to make Xwindow dump files
 
# cd /netapp/g7cwmspd/plotFiles/files
# /usr/sfw/bin/mogrify -format xwd *.jpg
 
#  Move files to web and to local zone MRADS cwmspixel directory for displaying by viewpix
 
echo 'Moving files to web server staging area and to local zone.'
cd /netapp/g7cwmspd/plotFiles/files
/bin/scp *.jpg g7cwmspd@nwo-wmlocal2.nwo.usace.army.mil:/mrads/cwmspixel
echo Done
