#!/bin/csh
source /usr1/g7cwmspd/.cshrc
setenv DISPLAY :1    
    jython /usr1/g7cwmspd/plotFiles/createPlotsMRRelev3.py
#    jython /usr1/g7cwmspd/plotFiles/createPlotsKanProj.py
#    jython /usr1/g7cwmspd/plotFiles/createPlotsMRRWaterTemp1.py
    jython /usr1/g7cwmspd/plotFiles/createPlotsMRRelev1.py
#    jython /usr1/g7cwmspd/plotFiles/createPlotsMRRpierre.py
#    jython /usr1/g7cwmspd/plotFiles/createPlotsMRRstage.py
#   jython /usr1/g7cwmspd/plotFiles/createPlotsNWKres.py
#    jython/usr1/g7cwmspd/plotFiles/createPlotsMRRresMin.py
#    jython/usr1/g7cwmspd/plotFiles/createPlotsMORiv2.py
#    jython/usr1/g7cwmspd/plotFiles/createPlotsMORiv1.py
#    jython/usr1/g7cwmspd/plotFiles/createPlotsMORiv.py
#   jython /usr1/g7cwmspd/plotFiles/createPlotsMRRcheckFUI.py
#    jython /usr1/g7cwmspd/plotFiles/createPlotsKanRiv.py
#    jython /usr1/g7cwmspd/plotFiles/createPlotsMRRfcastq_kg.py
#    jython /usr1/g7cwmspd/plotFiles/createPlotsMRRfcast4.py
#    jython /usr1/g7cwmspd/plotFiles/createPlotsMRRfui-qgh.py
##    jython /usr1/g7cwmspd/plotFiles/createPlotsMRRmainstem-qgh.py
#     jython /usr1/g7cwmspd/plotFiles/createPlotsMRRpierre.py
#     jython /usr1/g7cwmspd/plotFiles/createPlotsMRRpir.py
# jython /usr1/g7cwmspd/plotFiles/CroncompareFlows.py
#
# Prepare to make Xwindow dump files
#
#cd /usr1/g7cwmspd/plotFiles/files
#/usr/sfw/bin/mogrify -format xwd *.jpg
#
# Move files to web and to local zone MRADS cwmspixel directory for displaying by viewpix
#
echo 'Moving files to web server staging area and to local zone.'
cd /usr1/g7cwmspd/plotFiles/files
#/bin/scp -c3DES *.jpg rccdba@rotor.nwd-mr.usace.army.mil:/mrads/cwmspixel
/bin/scp *.jpg g7cwmspd@nwd-wmlocal1.nwo.usace.army.mil:/mrads/cwmspixel
echo Done
#rm *.jpg
