#!/bin/sh

# this shell script is used to view files created by dssVue scripting - grode 12/04
# PIXPATH = path where pixel files are located

PIXPATH='/usr1/g7cwmspd/plotFiles/files/'

echo 'Enter station (e.g. NCNE) to view or q to quit - Alt-F4 to close plot'
read ans
ans=`echo "$ans"|/usr/ucb/tr A-Z a-z`

# continue until user enters some form of quit

while test $ans
    do
	if test $ans = quit
	then
		exit 1
	fi

	if test $ans = q
	then
		exit 1
	fi

	# if the file exists display with imagemagick, if not tell user of non-existence


	if test -s $PIXPATH$ans.jpg
	then
	  /usr/sfw/bin/display -display `who am i | cut -f2 -d"(" | cut -f1 -d")"`:0 $PIXPATH$ans.jpg
#####	  /usr/sfw/bin/display $PIXPATH$ans.jpg
	else
		echo $ans 'DOES NOT EXIST!'
	fi

	# get another filename

	echo 'Enter station (e.g. NCNE) to view or q to quit - Alt-F4 to close plot'
	read ans
	ans=`echo "$ans"|/usr/ucb/tr A-Z a-z`

done
